type TSection = {
  p: string;
  h2: string;
  content?: string;
};

type TConfig = {
  html: {
    title: string;
    fullName: string;
    email: string;
  };
  hero: {
    name: string;
    p: string[];
  };
  contact: {
    form: {
      name: {
        span: string;
        placeholder: string;
      };
      email: {
        span: string;
        placeholder: string;
      };
      message: {
        span: string;
        placeholder: string;
      };
    };
  } & TSection;
  sections: {
    about: Required<TSection>;
    experience: TSection;
    feedbacks: TSection;
    works: Required<TSection>;
  };
};

export const config: TConfig = {
  html: {
    title: 'AI Arch — Where Ideas Construct Themselves',
    fullName: 'AI Arch',
    email: '@',
  },
  hero: {
    name: 'AI Arch',
    p: ['Where Ideas Construct Themselves'],
  },
  contact: {
    p: 'Profile & connect with us',
    h2: 'Profile.',
    form: {
      name: {
        span: 'Your Name',
        placeholder: "What's your name?",
      },
      email: { span: 'Your Email', placeholder: "What's your email?" },
      message: {
        span: 'Your Message',
        placeholder: 'What do you want to say?',
      },
    },
  },
  sections: {
    about: {
      p: '',
      h2: 'Overview.',
      content: `
       `,
    },
    experience: {
      p: 'Solution ',
      h2: 'Having Queries?',
    },
    feedbacks: {
      p: 'What others say',
      h2: 'Testimonials.',
    },
    works: {
      p: 'Introducing',
      h2: 'OUR PROJECTS',
      content: `Explore some of the stunning 3D architectural models generated by our AI. From futuristic offices to whimsical retreats, see what's possible when ideas construct themselves.`,
    },
  },
};
